-- 1. Criação dos tipos ENUM (globais no schema)
CREATE TYPE categoria_enum AS ENUM (
    'PROGRAMACAO', 'IA', 'FRONTEND', 'DADOS', 'INOVACAO', 'MARKETING', 'DESIGN'
);

CREATE TYPE status_enum AS ENUM (
    'NAO_RESPONDIDO', 'RESPONDIDO', 'RESOLVIDO'
);

CREATE TABLE cursos (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                nome VARCHAR(255) NOT NULL UNIQUE,
                categoria categoria_enum NOT NULL
);