CREATE TABLE topicos (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                titulo VARCHAR(255) NOT NULL,
                mensagem TEXT NOT NULL,
                autor VARCHAR(255) NOT NULL,
                categoria categoria_enum NOT NULL,
                data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                status status_enum NOT NULL DEFAULT 'NAO_RESPONDIDO',
                aberto BOOLEAN NOT NULL DEFAULT TRUE,
                quantidade_respostas INT NOT NULL DEFAULT 0,
                curso_id BIGINT,
    -- Chave estrangeira ligando com a tabela cursos
                CONSTRAINT fk_curso FOREIGN KEY (curso_id)
                REFERENCES cursos(id) ON DELETE SET NULL
);