CREATE TABLE respostas(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mensagem TEXT not null,
    autor varchar(255) not null,
    data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    solucao BOOLEAN DEFAULT FALSE,
    topico_id BIGINT,
    CONSTRAINT fk_topico foreign key (topico_id) references topicos(id) ON DELETE CASCADE
);