CREATE TABLE usuarios (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        email varchar(100) not null unique,
        senha varchar(100) not null,
        nome_completo VARCHAR(100) NOT NULL,
        nome_usuario VARCHAR(100) NOT NULL UNIQUE,
        mini_biografia VARCHAR(30),
        biografia TEXT
);
